# Development-friendly pre-commit hooks
# These hooks fix issues without failing, making development smoother

repos:
  # Basic file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']

  # Python linting only (no formatting to avoid conflicts)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [--fix, --select, I,E,W,F]  # Import sorting, errors, warnings, flake8

  # Local hooks
  - repo: local
    hooks:
      # Quick verification
      - id: verify-install
        name: Verify installation
        entry: ./scripts/run-verify.sh
        language: system
        pass_filenames: false
        description: Verify ZapGPT installation

# Settings
fail_fast: true
minimum_pre_commit_version: "3.0.0"
